base_path: '../../data/vitaldb'
holdout_subject_size: 100
test_size: 0.20
ch_names:
  - 'ABP'
  - 'ECG'
  - 'PPG'
ch_idx: 2
sfreq: 100
rfreq: 100
data_scaler: false
class_downsampling: true
data_augmentation_prob: 0.90

train_epochs: 30
train_warmup_epoch: 1
train_base_learning_rate: 0.0001
train_batch_size: 256
train_batch_accumulation: 1

second: 60
time_window: 3
time_step: 3
encoder_embed_dim: 512
encoder_heads: 8
encoder_depths: 6
decoder_embed_dim: 256
decoder_heads: 8
decoder_depths: 4
alpha: 1.0
projection_hidden:
  - 1024
  - 512
temperature: 0.1
mask_ratio: 0.8

print_point: 20
ckpt_path: '../../ckpt/vitaldb/'
model_name: 'neuronet'
