base_path: '../../data/sleep_edfx'
holdout_subject_size: 30
test_size: 0.20
ch_names:
  - 'EEG Fpz-Cz'
  - 'EEG Pz-Oz'
  - 'EOG horizontal'
ch_idx: 0
sfreq: 100
rfreq: 100
data_scaler: false
class_downsampling: false
data_augmentation_prob: 0.90

train_epochs: 50
train_warmup_epoch: 1
train_base_learning_rate: 0.0001
train_batch_size: 128
train_batch_accumulation: 1

second: 30
time_window: 4
time_step: 1
encoder_embed_dim: 512
encoder_heads: 8
encoder_depths: 6
decoder_embed_dim: 256
decoder_heads: 8
decoder_depths: 4
alpha: 1.0
projection_hidden:
  - 1024
  - 512
temperature: 0.1
mask_ratio: 0.8

print_point: 20
ckpt_path: '../../ckpt/sleep_edfx/'
model_name: 'neuronet'
